dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import dashboard_home


app_name = "dashboard"

urlpatterns = [

    # Home
    path("", login_required(dashboard_home), name="home"),
]   

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, upload_image, upload_paste_image
from landingpages.views import landing_page, thankyou_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('orders/', include('orders.urls')),
    path('landingpages/', include('landingpages.urls')),
    path('products/', include('products.urls')),
    path('stores/', include('stores.urls')),
    path('thankyou/<code>/', thankyou_page, name="thankyou_page"),
    path("upload/", upload_image, name="upload_image"),
    path("upload-paste/", upload_paste_image, name="upload_paste_image"),

    path('<str:code>/', landing_page, name="landing_page"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landingpages/urls.py
from django.urls import path
from . import views as landingpages
from . import views

app_name = "landingpages"

urlpatterns = [

    path("get_municipalities/<str:city_name>/", landingpages.get_municipalities, name='get_municipalities'),
    path("manage_cities/", views.manage_cities, name="manage_cities"),
    path("landing-pages/", views.landingpage_list, name="list"),
    path("create/<product_id>/", views.landingpage_create, name="create"),
    path("<str:pk>/", views.landingpage_detail, name="detail"),
    path("<str:pk>/edit/", views.landingpage_edit, name="edit"),
    path("<str:pk>/delete/", views.landingpage_delete, name="delete"),

]

orders/urls.py
from django.urls import path
from . import views as orders

app_name = "orders"

urlpatterns = [
    path("", orders.OrderListView.as_view(), name="orders_list"),
    
    
    path("<int:order_id>/details/", orders.order_detail_partial, name="order_detail_partial"),
    path("<int:order_id>/update/", orders.update_order, name="update_order"),
    path("<int:order_id>/order_client_info/", orders.order_client_info, name="order_client_info"),
    path("<int:order_id>/edit_client_info/", orders.edit_client_info, name="edit_client_info"),
    
    path("order_item/update/<int:item_id>/", orders.update_order_item, name="update_order_item"), 
    path("order_item/delete/<int:item_id>/", orders.delete_order_item, name="delete_order_item"),

    path("order/archive/<int:order_id>/", orders.archive_order, name="archive_order"),
    path("order/move_to_in_progress/<int:order_id>/", orders.move_to_in_progress, name="move_to_in_progress"),
    path("order/send_to_sheet/<int:order_id>/", orders.send_to_sheet, name="send_to_sheet"),

    path("status/", orders.order_status, name="order_status"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="products_list"),
    path('add/', views.add_product, name='add_product'),
    path("<int:pk>/", views.product_detail, name="product_detail"),
    path("<int:pk>/edit/", views.product_edit, name="edit_product"),

]

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def dashboard_home(request):
    return render(request, "dashboard/home.html")

templates/dashboard/layouts/navigation.html
{% load static %}
<nav id="mainNavbar" class="navbar navbar-vertical navbar-expand-lg scrollbar bg-dark navbar-dark">
            
    <!-- Theme configuration (navbar) -->
        <script>
            let navigationColor = localStorage.getItem('navigationColor'),
                navbar = document.getElementById('mainNavbar');
        
            if(navigationColor != null && navbar != null) {
                if(navigationColor == 'inverted') {
                    navbar.classList.add('bg-dark', 'navbar-dark');
                    navbar.classList.remove('bg-white', 'navbar-light');
                } else {
                    navbar.classList.add('bg-white', 'navbar-light');
                    navbar.classList.remove('bg-dark', 'navbar-dark');
                }
            }
        </script>    
    <div class="container-fluid">
        
        <!-- Brand -->
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo-small.png' %}" class="navbar-brand-img logo-light logo-small" alt="..." width="19" height="25">
            <img src="{% static 'images/logo.png' %}" class="navbar-brand-img logo-light logo-large" alt="..." width="125" height="25">

            <img src="{% static 'images/logo-dark-small.png' %}" class="navbar-brand-img logo-dark logo-small" alt="..." width="19" height="25">
            <img src="{% static 'images/logo-dark.png' %}" class="navbar-brand-img logo-dark logo-large" alt="..." width="125" height="25">
        </a>

        <!-- Navbar toggler -->
        <a href="javascript: void(0);" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#sidenavCollapse" aria-controls="sidenavCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </a>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenavCollapse">

            <!-- Navigation -->
            <ul class="navbar-nav mb-lg-7">
                {% comment %} <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{%  url 'dashboard:home' %}">
                        <svg viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18" xmlns="http://www.w3.org/2000/svg"><path d="M3.753,13.944v8.25h6v-6a1.5,1.5,0,0,1,1.5-1.5h1.5a1.5,1.5,0,0,1,1.5,1.5v6h6v-8.25" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M.753,12.444,10.942,2.255a1.5,1.5,0,0,1,2.122,0L23.253,12.444" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path></svg>
                        <span>Dashboard</span>
                    </a>
                </li> {% endcomment %}
            
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/orders/' %}active{% endif %}" href="{%  url 'orders:orders_list' %}">
                    <svg viewBox="0 0 20 20" class="nav-link-icon" height="30" width="30"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 19.1249H15.921C16.2753 19.125 16.6182 18.9996 16.889 18.7709C17.1597 18.5423 17.3407 18.2253 17.4 17.8759L20.037 2.37593C20.0965 2.02678 20.2776 1.70994 20.5483 1.48153C20.819 1.25311 21.1618 1.12785 21.516 1.12793H22.5"/>
                    <path stroke="currentColor" stroke-width="1.5" d="M7.875 22.125C7.66789 22.125 7.5 21.9571 7.5 21.75C7.5 21.5429 7.66789 21.375 7.875 21.375"/>
                    <path stroke="currentColor" stroke-width="1.5" d="M7.875 22.125C8.08211 22.125 8.25 21.9571 8.25 21.75C8.25 21.5429 8.08211 21.375 7.875 21.375"/>
                    <path stroke="currentColor" stroke-width="1.5" d="M15.375 22.125C15.1679 22.125 15 21.9571 15 21.75C15 21.5429 15.1679 21.375 15.375 21.375"/>
                    <path stroke="currentColor" stroke-width="1.5" d="M15.375 22.125C15.5821 22.125 15.75 21.9571 15.75 21.75C15.75 21.5429 15.5821 21.375 15.375 21.375"/>
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M17.9529 14.6251H5.88193C5.21301 14.625 4.5633 14.4014 4.03605 13.9897C3.5088 13.5781 3.13425 13.002 2.97193 12.3531L1.52193 6.55309C1.49426 6.44248 1.49218 6.32702 1.51583 6.21548C1.53949 6.10394 1.58827 5.99927 1.65846 5.90941C1.72864 5.81955 1.81839 5.74688 1.92089 5.69692C2.02338 5.64696 2.13591 5.62103 2.24993 5.62109H19.4839"/>
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 8.625V10.875"/>
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.5 8.625V10.875"/>
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 8.625V10.875"/>
                    </svg>
                    <span>Orders</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if '/products/' in  request.path %}active{% endif %}" href="{%  url 'products:products_list' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 34 34" height="25" width="25"><path d="M21.2,12.075l1.16,4.89a5.123,5.123,0,0,1-5.016,6.285H6.655a5.123,5.123,0,0,1-5.016-6.285L2.8,12.075" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/><path d="M9.75,14.25H6.583A4.289,4.289,0,0,1,2.25,10.007V6.75a1.5,1.5,0,0,1,1.5-1.5h16.5a1.5,1.5,0,0,1,1.5,1.5v3.257a4.289,4.289,0,0,1-4.333,4.243H14.25" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/><path d="M9.750 14.250 A2.250 2.250 0 1 0 14.250 14.250 A2.250 2.250 0 1 0 9.750 14.250 Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/><path d="M10.25.75h3.5a2,2,0,0,1,2,2v2.5a0,0,0,0,1,0,0H8.25a0,0,0,0,1,0,0V2.75A2,2,0,0,1,10.25.75Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg>
                    <span>Products</span>
                    </a>
                </li>

                
                <li class="nav-item">
                    <a class="nav-link {% if '/landing-pages/' in  request.path %}active{% endif %}" href="{%  url 'landingpages:list' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18"><defs><style>.a{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.5px;}</style></defs><title>common-file-double-1</title><path class="a" d="M17.25,23.25H3.75a1.5,1.5,0,0,1-1.5-1.5V5.25"></path><rect class="a" x="5.25" y="0.75" width="16.5" height="19.5" rx="1" ry="1"></rect></svg>                    <span> Landing Pages</span>
                    </a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link {% if '/manage_cities/' in  request.path %}active{% endif %}" href="{%  url 'landingpages:manage_cities' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 55 55"><defs><style>.a{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;}</style></defs><path class="a" d="M27.5944,5.5948a9.0331,9.0331,0,0,0-9.0331,9.0331c0,7.0693,6.8966,15.5761,8.7032,17.6655a.5577.5577,0,0,0,.7855.055l.0549-.055c1.7831-2.0973,8.5226-10.5962,8.5226-17.6655A9.0331,9.0331,0,0,0,27.5944,5.5948Zm0,12.8548a4.4344,4.4344,0,1,1,4.4344-4.4344v.0113A4.4344,4.4344,0,0,1,27.5944,18.45Z"/><polyline class="a" points="36.454 16.678 37.629 16.598 42.5 40.607 32.376 42.405 16.461 40.723 5.5 42.405 8.458 17.758 17.447 16.598 18.736 16.662"/><line class="a" x1="17.4467" y1="16.598" x2="16.8049" y2="40.7598"/><line class="a" x1="32.3758" y1="42.4052" x2="30.6655" y2="28.982"/></svg>
                    <span> Cities</span>
                    </a>
                </li>

                
            </ul>
            <!-- End of Navigation -->

        </div>
        <!-- End of Collapse -->
    </div>
</nav>